### ISSUE TITLE
Add galaxy as partner

### ISSUE THREAD

**Issue by paulzierep** [research-software-ecosystem/research-software-ecosystem.github.io#1]
So I do not forget: add Galaxy here: https://github.com/research-software-ecosystem/research-software-ecosystem.github.io/blob/main/_data/tool_and_resource_list.yml

**Comment by paulzierep** [comment]
Add @bgruening @paulzierep @arash77 to https://github.com/research-software-ecosystem/research-software-ecosystem.github.io/blob/main/_data/CONTRIBUTORS.yml

**Comment by hmenager** [comment]
Thanks @paulzierep. Would you be ok creating the corresponding PRs?

**Comment by paulzierep** [comment]
Sure this was just a reminder for me: https://github.com/research-software-ecosystem/research-software-ecosystem.github.io/pull/3 and https://github.com/research-software-ecosystem/research-software-ecosystem.github.io/pull/4

**Comment by hmenager** [comment]
Solved!
