### ISSUE TITLE
Change positioning of GitHub logo and text in main RSec drawing

### ISSUE THREAD

**Issue by jmfernandez** [research-software-ecosystem/research-software-ecosystem.github.io#2]
From my point of view, GitHub logo and text positioned over the center of the whirl at https://github.com/research-software-ecosystem/research-software-ecosystem.github.io/blob/dfc7a16d9b1f3064f188cd6738fc73cd4d6afd21/assets/img/rsec.svg 

![image](https://github.com/research-software-ecosystem/research-software-ecosystem.github.io/assets/2072150/533a30bb-54b8-4621-b63c-a9154f476adb)

should be either relocated, or changed its color from black to white, cyan or similar, or give it a semitransparent white background, so it is distinguishable.

**Comment by hmenager** [comment]
Indeed, this part of the diagram is completely unreadable. The colors were changed when I edited the file with Libre Office. Needs some work!
